CONFIG_LOG=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_GPIO_ESP32=y
# CONFIG_ESP32_USE_UNSUPPORTED_REVISION is not available in v3.7.0

CONFIG_LORA=y
CONFIG_I2C=y
CONFIG_DISPLAY=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_SSD1306=y
CONFIG_SSD1306_DEFAULT_CONTRAST=128

CONFIG_SYS_HEAP_RUNTIME_STATS=y  
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_THREAD_STACK_INFO=y  
CONFIG_THREAD_RUNTIME_STATS=y  
CONFIG_INIT_STACKS=y 
